permalink: /:title

plugins: [jekyll-paginate]
paginate: 1
paginate_path: /page:num/

sass:
  style: compressed

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
