permalink: /:title

sass:
  style: compressed

collections:
  writing:
    output: true
  reading: 
    output: true
  photos: 
    output: true

defaults:
  - scope:
      path: ""
      type: "writing"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "reading"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "photos"
    values:
      layout: "photo"
  - scope:
      path: ""
    values:
      layout: "default"